Update duplicity to 0.7.17
Summary:
* Removed changes made in bugfix "Provide a file history feature"
  - Changes required too much memory to carry in the manifest
  - The option --file-changed in collection-status is now invalid
  - Starting a full backup will be needed to fully utilize this fix
* Fix update of Launchpad Translations.  Translations were not being picked
  up on a daily basis and we got several months behind.
* Fixed bug AttributeError: 'GPGError' object has no attribute 'decode'
  - Replaced call to util.ufn() with call to util.uexc().  Stupid typo!
* More fixes for Unicode handling
  - Default to 'utf-8' if sys.getfilesystemencoding() returns 'ascii' or None
* Patched in lp:~crosser/duplicity/fix-oauth-flow
  - Fixed "BackendException with oauth2client 4.0.0"
* Patched in lp:~crosser/duplicity/dpbx-fix-file-listing
  - Fixed "Dropbox support needs to be updated for Dropbox SDK v7.1"
* Patched in lp:~crosser/duplicity/fix-small-file-upload
  - Fixed small file upload changes made in Dropbox SDK v7.1
* Fix pylint error in webdavbackend.py

Depends on D2435

Signed-off-by: Pierre-Yves <pyu@riseup.net>

Test Plan: `duplicity full /tmp/dup/ rsync://py@192.168.1.31:22/public/`

Reviewers: #triage_team, DataDrake

Reviewed By: #triage_team, DataDrake

Subscribers: DataDrake

Differential Revision: https://dev.solus-project.com/D2436